{
  extends: airbnb,

  "parser": "babel-eslint",

  "env" : {
    "node" : true,
    "es6" : true
  },

  "parserOptions": {
    "sourceType": "module",
    "allowImportExportEverywhere": false,
    "codeFrame": false
  },

  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  }
}